- name: "backend"
  color: "ef476f"
  description: ""
- name: "bug"
  color: "ff006e"
  description: ""
- name: "devops"
  color: "3a86ff"
  description: ""
- name: "epic"
  color: "8338ec"
  description: ""
- name: "frontend"
  color: "06d6a0"
  description: ""
- name: "idea"
  color: "90e0ef"
  description: ""
- name: "infrastructure"
  color: "118ab2"
  description: ""
- name: "good-first-issue"
  color: "d0d1ff"
  description: ""
- name: "ready-to-merge"
  color: "d876e3"
  description: ""
- name: "request-for-review"
  color: "7209b7"
  description: ""
- name: "roadmap"
  color: "4895ef"
  description: ""
- name: "ui"
  color: "00f5d4"
  description: ""
- name: "priority:1"
  color: "07beb8"
  description: ""
- name: "priority:2"
  color: "3dccc7"
  description: ""
- name: "priority:3"
  color: "68d8d6"
  description: ""
- name: "priority:4"
  color: "9ceaef"
  description: ""
- name: "priority:5"
  color: "c4fff9"
  description: ""
