name: Auto Approve
on: pull_request
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - if: github.actor == 'shunkakinoki'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            github.pulls.createReview({
              pull_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              event: 'APPROVE',
            })
      - if: github.actor == 'renovate[bot]'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            github.pulls.createReview({
              pull_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              event: 'APPROVE',
            })
