name: Labels
on:
  push:
    branches:
      - alpha
      - beta
      - main
jobs:
  labels:
    if: github.actor != 'sentrei-bot'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
