name: Release
on:
  push:
    branches:
      - alpha
      - beta
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - id: nvm
        run: |
          echo ::set-output name=NVMRC::$(cat .nvmrc)
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
          always-auth: false
          registry-url: https://registry.npmjs.org/
          scope: "@sentrei"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - id: yarn-cache-dir
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir.outputs.dir }}
          key: |
            yarn-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "sentrei-bot"
          GIT_COMMITTER_NAME: "sentrei-bot"
          GIT_AUTHOR_EMAIL: "70007101+sentrei-bot@users.noreply.github.com"
          GIT_COMMITTER_EMAIL: "70007101+sentrei-bot@users.noreply.github.com"
